name: Install and execute

on:
  release:
    types: [published]
  schedule:
    - cron: '12 * * * *'

jobs:
  test-unix:
    name: "Testing ${{ matrix.version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, macos-12, macos-13, ubuntu-20.04, ubuntu-22.04 ]
        version: [ '2.5', '2.4', '2.3', '2.2' ]
    steps:
      - uses: actions/checkout@v3
      - name: Test on ${{ matrix.os }}
        run: |
          curl --fail -s https://get.simplelocalize.io/${{ matrix.version }}/install | bash
          simplelocalize --version
  test-windows:
    name: "Testing ${{ matrix.version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2022 ]
        version: [ '2.5', '2.4', '2.3', '2.2']
    steps:
      - uses: actions/checkout@v3
      - name: Test on ${{ matrix.os }}
        run: |
          . { iwr -useb https://get.simplelocalize.io/${{ matrix.version }}/install-windows } | iex;
          simplelocalize --version
